version: '3'

services:
  mysql:
      image: mysql:8.0.15
      command: --default-authentication-plugin=mysql_native_password
      container_name: ORM_Test
      ports:
        - 3318:3306
      volumes:
        - ~/Database/ORM_Test:/var/lib/mysql
        
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ORM_Test
        MYSQL_USER: orm_test
        MYSQL_PASSWORD: qweasdzxc

        